### ISSUE TITLE
Proof of concept: Allow external IAM providers to use TIB to enable SSO within Tyk

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk-identity-broker#13]
Sub-task of: https://github.com/TykTechnologies/product/issues/11

External providers use modern standards such as OIDC, and take care of LDAP and SAML themselves. TIB should be pretty much ready to handle any interaction with the providers, but we need a PoC to make sure.

### Try to integrate with:
* Okta
* Ping

**Comment by nickReyn** [comment]
TIB supports OAuth-based SSO, and all we would need to do is write OAuth handlers for Ping and Okta

**Comment by lonelycode** [comment]
Basically TIB already has an OAuth wrapper library that it uses that wraps[goth](https://github.com/markbates/goth), if you look at the gothic code there's a bunch of providers:

https://github.com/markbates/goth/tree/master/providers

It's quite easy to extend and write custom ones - adding one for a platform like Ping or Okta should be possible, though handling config might be tricky since I bet that these providers give non-public endpoints.

Nonetheless, if we have an OAuth handler for one of these platforms, using TIB as an auth layer to pass through to gateway, dashboard or portal should be instant with existing handlers.

**Comment by lonelycode** [comment]
Just noticed thay added an Auth0 handler, we shoudl enable that anyway, that's super :-)

**Comment by buger** [comment]
Done, now Tib has support for any OpenID connect provider
